In [3]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('./pet_metadata.csv')

In [6]:
data

,type,species,mission-id,provider-code,breed,age,class,sex,weight,shoulder-height,...,disease,diseaseName,CRP,lgG,IL-6,AFP,heart-rate,breating-rate,body-heat,stress
0,B,10,10_001074,16,DRI,10.10,SS,CM,8.80,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
1,B,10,10_000929,16,CHI,11.10,SS,SF,2.50,19.0,...,ABN,CAR,1.48,8.68,4.44,0.55,142,33,38.1,8.6
2,B,10,10_000957,16,CHI,8.00,SS,SF,1.80,17.0,...,NOR,NaN,0.29,6.78,3.27,0.54,110,36,40.0,3.6
3,B,10,10_001074,16,DRI,10.10,SS,CM,8.80,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
4,B,10,10_000929,16,CHI,11.10,SS,SF,2.50,19.0,...,ABN,CAR,1.48,8.68,4.44,0.55,142,33,38.1,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,B,10,10_000929,16,CHI,11.10,SS,SF,2.50,19.0,...,ABN,CAR,1.48,8.68,4.44,0.55,142,33,38.1,8.6
144,B,10,10_001073,16,POO,5.25,SS,CM,3.86,22.0,...,NOR,NaN,1.15,10.76,3.60,0.55,142,33,40.0,8.9
145,B,10,10_000957,16,CHI,8.00,SS,SF,1.80,17.0,...,NOR,NaN,0.29,6.78,3.27,0.54,110,36,40.0,3.6
146,B,10,10_001075,16,POO,8.00,SS,CM,8.30,30.0,...,NOR,NaN,0.72,4.09,4.47,0.54,124,36,38.4,3.2
147,B,10,10_001073,16,POO,5.25,SS,CM,3.86,22.0,...,NOR,NaN,1.15,10.76,3.60,0.55,142,33,40.0,8.9

In [9]:
data['mission-id'].nunique()

8

In [10]:
data['mission-id'].unique()

array(['10_001074', '10_000929', '10_000957', '10_000930', '10_001073',
       '10_001088', '10_000928', '10_001075'], dtype=object)

In [12]:
data.loc[data['mission-id'] == '10_001074']

,type,species,mission-id,provider-code,breed,age,class,sex,weight,shoulder-height,...,disease,diseaseName,CRP,lgG,IL-6,AFP,heart-rate,breating-rate,body-heat,stress
0,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
3,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
6,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
10,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
17,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
23,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
24,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
50,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
54,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
55,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
63,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
74,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
88,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
90,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
107,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
119,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
121,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
128,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
134,B,10,10_001074,16,DRI,10.1,SS,CM,8.8,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3

In [18]:
data.loc[data['mission-id'] == '10_001074'][['species', 'age', 'weight', 'CRP',
                                             'lgG' ,'IL-6', 'AFP', 'heart-rate',
                                             'breating-rate', 'body-heat', 'stress']].diff(axis = 0)

,species,age,weight,CRP,lgG,IL-6,AFP,heart-rate,breating-rate,body-heat,stress
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
88,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# metadata는 같은 mission-id를 갖는 강아지들에 대해서 같은 값을 가지는 것으로 보임 -> drop_duplicates 해야 함

# 그러면 총 8마리 강아지

In [20]:
newdata = data.drop_duplicates('mission-id')

In [26]:
newdata

,type,species,mission-id,provider-code,breed,age,class,sex,weight,shoulder-height,...,disease,diseaseName,CRP,lgG,IL-6,AFP,heart-rate,breating-rate,body-heat,stress
0,B,10,10_001074,16,DRI,10.10,SS,CM,8.80,24.5,...,NOR,NaN,2.85,4.96,1.86,0.57,108,24,38.9,1.3
1,B,10,10_000929,16,CHI,11.10,SS,SF,2.50,19.0,...,ABN,CAR,1.48,8.68,4.44,0.55,142,33,38.1,8.6
2,B,10,10_000957,16,CHI,8.00,SS,SF,1.80,17.0,...,NOR,NaN,0.29,6.78,3.27,0.54,110,36,40.0,3.6
5,B,10,10_000930,16,POM,4.10,SS,CM,6.86,31.0,...,NOR,NaN,6.55,5.92,2.82,0.55,120,21,38.7,1.8
7,B,10,10_001073,16,POO,5.25,SS,CM,3.86,22.0,...,NOR,NaN,1.15,10.76,3.60,0.55,142,33,40.0,8.9
9,B,10,10_001088,10,POO,2.00,SS,CM,8.80,34.0,...,NOR,NaN,0.24,5.10,2.11,0.55,84,24,39.0,1.3
12,B,10,10_000928,16,ETC,5.50,SS,CM,11.00,30.0,...,NOR,NaN,0.33,9.62,3.14,0.55,142,38,38.4,2.7
14,B,10,10_001075,16,POO,8.00,SS,CM,8.30,30.0,...,NOR,NaN,0.72,4.09,4.47,0.54,124,36,38.4,3.2

In [27]:
newdata.breed.nunique()

5

In [29]:
newdata.BCS.value_counts()

5    3
6    2
4    2
7    1
Name: BCS, dtype: int64

In [28]:
newdata.iloc[0, :]

type                       B
species                   10
mission-id         10_001074
provider-code             16
breed                    DRI
age                     10.1
class                     SS
sex                       CM
weight                   8.8
shoulder-height         24.5
neck-size               30.0
back-length               37
chest-size              46.5
BCS                        6
body-part                 11
exercise                   2
food-count                 2
environment                1
defecation                 1
food-amount             0.49
snack-amount              10
food-kind                  1
disease                  NOR
diseaseName              NaN
CRP                     2.85
lgG                     4.96
IL-6                    1.86
AFP                     0.57
heart-rate               108
breating-rate             24
body-heat               38.9
stress                   1.3
Name: 0, dtype: object